USE [master]
GO

/****** Object:  Database [CatalogoWebDBNaN]    Script Date: 29/7/2024 15:38:14 ******/
/******
CREATE DATABASE [CatalogoWebDBNaN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CatalogoWebDBNaN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CatalogoWebDBNaN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CatalogoWebDBNaN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CatalogoWebDBNaN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CatalogoWebDBNaN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
******/
ALTER DATABASE [CatalogoWebDBNaN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ARITHABORT OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET  MULTI_USER 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CatalogoWebDBNaN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CatalogoWebDBNaN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CatalogoWebDBNaN] SET QUERY_STORE = ON
GO

ALTER DATABASE [CatalogoWebDBNaN] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CatalogoWebDBNaN] SET  READ_WRITE 
GO


CREATE TABLE USERS(
	Id int PRIMARY KEY,
	Email varchar(100),
	Pass varchar(50),
	Nombre varchar(50),
	Apellido varchar(50),
	UrlImagenPerfil varchar(100),
	administrador bit
)
CREATE TABLE FAVORITOS(
	Id int PRIMARY KEY,
	IdUser int,
	idArticulo int,
	CONSTRAINT FK_Fav_Users FOREIGN KEY(IdUser) REFERENCES USERS(Id),
	CONSTRAINT FK_Fav_Art FOREIGN KEY(IdArticulo) REFERENCES ARTICULOS(Id)
)

CREATE TABLE CATEGORIAS(
	Id int PRIMARY KEY,
	Descripcion varchar(50)
)
CREATE TABLE MARCAS(
	Id int PRIMARY KEY,
	Descripcion varchar(50)
	)
CREATE TABLE ARTICULOS(
	Id int PRIMARY KEY,
	Codigo varchar(30),
	Nombre varchar(50),
	Descripcion varchar(100),
	IdMarca int,
	IdCategoria int,
	ImagenUrl varchar(50),
	Precio float
	)
CREATE TABLE ARTICULOS_MARCAS(
	IdArticulos int,
	IdMarcas int,
	CONSTRAINT FK_Articulos FOREIGN KEY (IdArticulos) REFERENCES ARTICULOS(Id),
	CONSTRAINT FK_Marcas FOREIGN KEY (IdMarcas) REFERENCES MARCAS(Id)
)