USE [master]
GO

/****** Object:  Database [GaleriaDeArteDB]    Script Date: 29/7/2024 17:53:56 ******/
CREATE DATABASE [GaleriaDeArteDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GaleriaDeArteDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GaleriaDeArteDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GaleriaDeArteDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\GaleriaDeArteDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GaleriaDeArteDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GaleriaDeArteDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GaleriaDeArteDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GaleriaDeArteDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GaleriaDeArteDB] SET  MULTI_USER 
GO

ALTER DATABASE [GaleriaDeArteDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GaleriaDeArteDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GaleriaDeArteDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GaleriaDeArteDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GaleriaDeArteDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GaleriaDeArteDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [GaleriaDeArteDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GaleriaDeArteDB] SET  READ_WRITE 
GO


CREATE TABLE Exposiciones(
	Id int PRIMARY KEY,
	Nombre varchar(25),
	FechaInicio date,
	FechaFin date
	)
CREATE TABLE Artistas(
	Id int PRIMARY KEY,
	Nombre varchar(25),
	Pais varchar(50)
	)
CREATE TABLE Obras(
	Id int PRIMARY KEY,
	Titulo varchar(50),
	Estilo varchar(30),
	IdArtista int
)
CREATE TABLE [ObrasExposiciones](
	IdObra int,
	IdExposicion int,
	CONSTRAINT FK_ObrasExposiciones_obra FOREIGN KEY (IdObra) REFERENCES Obras(Id),
	CONSTRAINT FK_ObrasExposiciones_Expo FOREIGN KEY (IdExposicion) REFERENCES Exposiciones(id)
	)